name: Messiah Push

on:
  push:
    branches: [main, master] # Déclenche seulement sur les branches principales

jobs:
  build-and-release:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner
        with:
          fetch-depth: 0 # Nécessaire pour obtenir tous les tags

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U pyinstaller
          python -m pip install -U customtkinter
          python -m pip install -U Pillow
          python -m pip install -U CTkMessageBox

      #    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --add-data "resources/icons/messiah.ico:." --add-data "resources:resources" --icon=resources/icons/messiah.ico --name=messiah_patch main.py

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Messiah
          files: dist/messiah_patch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
