name: Messiah Push

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pyinstaller
          python -m pip install -U customtkinter
          python -m pip install -U Pillow
          python -m pip install -U CTkMessageBox
        # python -m pip install -U tkinter
      #    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --add-data "messiah.ico:." --add-data "icons8-search-50-dark-theme.png:." messiah_patch.py
        # pyinstaller --onefile --windowed messiah_patch.py

      #- name: Archive executable
      #  run: |
      #    7z a my_script.zip dist/messiah_patch.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: messiah_patch
          path: dist/messiah_patch.exe
